config/routes.rb
Rails.application.routes.draw do
  get 'reports/all_data'

  get 'reports/main'
  post 'reports/thank_you'
  root 'reports#main'

end

app/models/assembly.rb
class Assembly < ActiveRecord::Base
  has_many :sequences
end

app/models/gene.rb
class Gene < ActiveRecord::Base
  belongs_to :sequence
  has_many :hits, as: :subject

  validates :sequence_id, presence: true
end

app/models/hit.rb
class Hit < ActiveRecord::Base
  belongs_to :subject, polymorphic: true

  validates :subject_id, presence: true
  validates :subject_type, presence: true
end

app/models/sequence.rb
class Sequence < ActiveRecord::Base
  belongs_to :assembly
  has_many :genes

  validates :assembly_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def main
  end

  def thank_you
    @email = params[:email]
    @assembly = params[:assembly]
    ProcessAssemblyJob.perform_later(@assembly, @email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DatabaseOptimizations</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p id="notice"><%= notice %></p>
<%= yield %>

</body>
</html>

app/views/reports/all_data.html.erb
<h1>Hits for <%= @assembly.name %></h1>
<p>Number of hits: <%= @hits.length %></p>

<table>
  <thead>
    <tr>
      <th>Matching Gene Name</th>
      <th>Matching DNA</th>
      <th>Percent Similarity</th>
    </tr>
  </thead>
  <tbody>
    <% @hits.each do |h| %>
      <tr>
        <td><%= h.match_gene_name %></td>
        <td><%= h.match_gene_dna.first(100) %></td>
        <td><%= h.percent_similarity %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reports/main.html.erb
<%= form_tag(reports_thank_you_path) do%>

<%= text_field_tag :email, nil, placeholder: "email" %>
<%= text_field_tag :assembly, nil, placeholder: "assembly" %>

<%= submit_tag "submit" %>

<% end %>

app/views/reports/thank_you.html.erb
<h1>Thanks, dude</h1>
<p>We will send an email to <%= @email %> as soon as it has been processed</p>